### ISSUE TITLE
Add tags to your blog post entries

### ISSUE THREAD

**Issue by troygrosfield** [tristinwells/tristinwells.com#28]
Blog entries should have a be taggable.  Tags are a way for users to help find content in your site.  To do this, you'll integrate in the [django-taggit](https://github.com/alex/django-taggit) app.
- http://django-taggit.readthedocs.org/en/latest/

**TODOs**
- [ ]  create a new branch for all these changes.  I want to see all work completed in this branch and a PR when this is finished to the master branch.
- [ ] install and add [django-taggit](https://github.com/alex/django-taggit) to your INSTALLED_APPS settings
- [ ] run `python manage.py migrate` command to create any new tables needed
- [ ] add tags to your `Entry` model
- [ ] update your forms to include a field to add tags. See:
  - http://django-taggit.readthedocs.org/en/latest/forms.html
- [ ] create a new page located at `/tags/&lt;tag_slug>` that displays all of your Entries (ListView) by tags.  So when I go to the following url: `/tags/hello` it shows me all blog posts that have been tagged with "hello".

**Comment by troygrosfield** [comment]
Tags in my blog show up at the bottom of the blog entry:

![screen shot 2015-06-29 at 1 36 35 pm](https://cloud.githubusercontent.com/assets/1551551/8416757/13c5beee-1e65-11e5-948a-07768e299861.png)

**Comment by troygrosfield** [comment]
@tristinwells, make sure old tasks are getting cleaned up.
