### ISSUE TITLE
Add font-awesome icons to your site

### ISSUE THREAD

**Issue by troygrosfield** [tristinwells/tristinwells.com#33]
Add font-awesome to you site so you can add icons to help with the visual side of your site:
- http://fortawesome.github.io/Font-Awesome/examples/

**TODOs**
- [ ] download font awesome files
  - http://fortawesome.github.io/Font-Awesome/
- [ ] move the downloaded files to a folder in your `statics` folder called `font-awesome`
- [ ] add the font files and css files to your html files so you can use the markup to add images
- [ ] add images that your site that you feel add benefit
  - http://fortawesome.github.io/Font-Awesome/icons/
