### ISSUE TITLE
Add an avatar to your user

### ISSUE THREAD

**Issue by troygrosfield** [tristinwells/tristinwells.com#37]
http://en.gravatar.com/ is a site that lets you add a avatar by email address.  You can then use this avatar on your site.

**TODOs**
- [ ] Sign up for an account at http://en.gravatar.com/
- [ ] add the [django-gravatar2](https://github.com/twaddington/django-gravatar/) dependency to your site
- [ ] add the authenticated user's gravatar (avatar) on your site in the header somewhere.
